language: go

go:
  - 1.11.x

env:
  - DEP_VERSION="0.4.1"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -vendor-only

before_script:
  - npm install -g truffle@4.1.14 ganache-cli@6.2.3

script:
  - ganache-cli -m=plasma > /dev/null &
  - sleep 5
  - cd contracts/
  - npm install
  - truffle migrate
  - cd ../
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
